# Generated by Django 3.1.5 on 2021-01-10 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20210110_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
